#' ---
#' title: "WBE for SARS-CoV-2 in Switzerland: model development (C) "
#' author: "Julien Riou"
#' date: "`r Sys.Date()`"
#' params:
#'    controls: controls
#' output:
#'    html_document:
#'      code_folding : hide
#'      toc: true
#'      toc_float: true
#'      toc_depth: 4
#'      number_sections: true
#'      highlight: pygments
#'      theme: cosmo
#'      link-citations: true
#' ---


#+ results="hide", warnings="false", echo="false"
source("setup.R")
ww1 = readRDS(fs::path("../",controls$savepoint,"ww1.rds"))
# plot function
ppp_day = function(dat,mod) {
  mod$summary.fitted.values %>% 
    dplyr::bind_cols(dat) %>% 
    ggplot(aes(x=date)) +
    geom_point(aes(y=logrep)) +
    geom_ribbon(aes(ymin=`0.025quant`,ymax=`0.975quant`),alpha=.5,fill=cust_cols[1]) +
    geom_line(aes(y=mean),colour=cust_cols[1]) +
    annotate(x=min(dat$date),y=min(dat$logrep),geom="text",label=paste0("WAIC=",round(mod$waic$waic)),hjust=0)
}

#' 
#'  
#+ fig.width=8, fig.height=7.5
# select one ARA
chosen_ara = "Aarau"
# select parameters
Q = 400 # wastewater generated by one person (L/day)
S = 1.9e6 # shedding rate (gc/ml)
V = 128*1.06 # stool volume (g/person/day)

# data management
ww_one = ww1 %>% 
  filter(ara_name==chosen_ara) %>% 
  # remove missing
  filter(!is.na(vl)) %>%
  # prevalence
  mutate(prev= conc * Q / (S*V)) %>% 
  # log
  mutate(logvl=log(vl),
         logrep=log(reported_cases+1),
         loghos=log(reported_hospit+1)) %>% 
  # manage dates
  mutate(day=as.numeric(date)-min(as.numeric(date)),
         weekend=if_else(lubridate::wday(date,week_start=1)>=5,1,0)) %>% 
  rownames_to_column()
# plot
ww_one %>% 
  ggplot(aes(x=date)) +
  geom_point(aes(y=prev))
